### PR TITLE
Fix typo in the Google plugin docstring

### PR DESCRIPTION
**Pull request by kwk**

### CODE REVIEW

**Comment by kwk** [comment]
@psss is this repo no longer maintained?

**Comment by psss** [comment]
Sorry for the slow feedback, just too many things on my plate. Could you please allow push to your branch?

**Review by psss — APPROVED** [review]
Thanks for fixing this!

**Comment by kwk** [comment]
@psss sorry for the provocative comment. I didn't want to rush you. Thank you for merging this. I hope you find the time to take a look at the other PRs I've opened for you here.

**Pull request merged**
