### PR TITLE
Fix JIRA basic login issue

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #163

### CODE REVIEW

**Comment by geoand** [comment]
I am not a python expert, so this might not be the best way of doing things, but it at least seemed to work around the JIRA login problem for me

**Comment by psss** [comment]
Thanks for the patch, @geoand. I looked a bit into the requests docs and it seems the solution could be even more straight forward:

    requests.get('https://api.github.com/user', auth=('user', 'pass'))

I've tried to use this approach in 99280c0 and it works for me fine. Could you confirm that it works for you as well? Thanks.

**Comment by geoand** [comment]
You are welcome @psss !

I tried the change you mention and it does indeed work. The only difference I see is that the response in the case of my patch contains a `session` object (which contains things like the `JSESSIONID`). I am note sure if that section are needed or not...

**Comment by psss** [comment]
Great! Thanks for verification. Not sure about the `session` object but created/resolved issues seem to be reported correctly so let's keep it simple.

**Comment by geoand** [comment]
Sounds good :)

Thanks!

**Pull request closed without merging**
