### PR TITLE
Support custom xmlrpc endpoint for MoinMoin wiki

### LINKED ISSUE #239: [wiki] not working with python-3.9
xmlrpc.client now ignores query in URI ("?action=xmlrpc2")
working version: https://github.com/python/cpython/blob/3.8/Lib/xmlrpc/client.py
```
send: b'POST /?action=xmlrpc2 HTTP/1.1\r\nHost: wiki.test.redhat.com\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.8\r\nContent-Length: 197\r\n\r\n'
send: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>getRecentChanges</methodName>\n<params>\n<param>\n<value><dateTime.iso8601>20210301T00:00:00</dateTime.iso8601></value>\n</param>\n</params>\n</methodCall>\n"
```
new version: https://github.com/python/cpython/blob/3.9/Lib/xmlrpc/client.py
```
send: b'POST / HTTP/1.1\r\nHost: wiki.test.redhat.com\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.9\r\nContent-Length: 197\r\n\r\n'
send: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>getRecentChanges</methodName>\n<params>\n<param>\n<value><dateTime.iso8601>20210301T00:00:00</dateTime.iso8601></value>\n</param>\n</params>\n</methodCall>\n"
```
I tried to encode it ('{0}%3Faction=xmlrpc2'.format(url)) or pass this option as header, without success.

My ideas:
* file issue for xmlrpc.client
* use some other library
* use alternative url if exists

### PR DESCRIPTION
**Pull request by psss**
Resolves #239.

### CODE REVIEW

**Comment by psss** [comment]
This seems to be working fine with the new `RPC2` endpoint provided by @mrc0mmand. Example config:

    [wiki]
    type = wiki
    api = RPC2
    wiki test = http://the.wiki.server/

@AsciiWolf, @optak, please give it a try and let me know if it works for you. Thanks.

**Comment by AsciiWolf** [comment]
@psss It seems that wiki.brq does not support RPC2 so I had to comment it out in did config, however it works fine with wiki.test. Thanks! :-)

**Comment by mrc0mmand** [comment]
> @psss It seems that wiki.brq does not support RPC2 so I had to comment it out in did config, however it works fine with wiki.test. Thanks! :-)

Yeah, I wasn't sure if this will be the final solution, so I haven't reconfigured the BRQ wiki yet. Will do that next week.

**Comment by psss** [comment]
> it works fine with wiki.test

Good to hear! Thanks for the verification.

**Comment by psss** [comment]
> I haven't reconfigured the BRQ wiki yet. Will do that next week.

Nice, thanks a lot!

**Comment by optak** [comment]
LGTM

**Review by optak — APPROVED** [review]

**Comment by psss** [comment]
Thanks for the review. Merging.

**Pull request merged**
