### PR TITLE
0.4.1-2

### PR DESCRIPTION
**Pull request by kejbaly2**
(squashed some of the commits)

```
+ Sun Sep 07 2015 Chris Ward <cward@redhat.com> 0.4.1-1
+- Invoke tasks.py: build, test, clean_git, ...
+- MrBob Project Templates: plugin, py_file
+- pep8 fixes
+- log fixes: pass name to Logging on intiation
+- enable package dependency extra's installation
+- change default sphinx template: readthedocs
+- flatten package directory (eg, /sources/did->/did)
```

### CODE REVIEW

**Comment by kejbaly2** [comment]
I figure one 0.4.1 pull request would be easier to review than each of the invidiuals ones. Let me know if you see anything you don't like.

**Comment by psss** [comment]
As I said before, reviewing & merging such large pull requests is
not very efficient. It makes much more sense to me to have commits
related to one feature in a single branch and pull request.

Regarding version bumps and change log entries, I believe it's
better to do this just once when everything is done. If commit
messages are well formed (ideally starting with capital letter)
it's easy to filter interesting ones and just copy & paste them.

I'm going to look through patches now as individual pull requests
have been all closed by removing their corresponding branches.

**Comment by kejbaly2** [comment]
damn; i thought it would be easier to pull them in as a bunch; the commits
are grouped pretty tightly. But OK, i'll revert back to branching and
sending pull requests for all groups and individual changes and leave you
to bump versions, update change logs and so forth.

I'll do it now. Sorry again for the trouble.

**Comment by psss** [comment]
I have reviewed your patches in 0.4.1-2 and pushed mr.bob to
master, a little bit modified, as 0b7274f. I think content
such as templates fits well to examples. I'm not sure about the
invoke thing. It seems like duplicating what Makefile does?

**Comment by kejbaly2** [comment]
Yes, invoke is a python based makefile; please consider it; i don't think
it hurts to have them both. I prefer working in python.

**Pull request closed without merging**
