### PR TITLE
add basic GitLab support

### PR DESCRIPTION
**Pull request by evgeni**
fixes: #129

### CODE REVIEW

**Comment by psss** [comment]
Thanks for the patch, Evgeni. Looks fine. Just a few comments: Could you include a couple of tests for the new plugin? (Is there a public gitlab instance which could be used?) I would recommend to always avoid one-letter variable names and rather use format() instead of "%" operator for text formatting.

Last two comments are just a nitpicks from general recommendations to keep stuff consistent:

 * When using hanging indent, the first line should be empty.
 * Commit: Complete sentence with the first word capitalized.

See also: http://did.readthedocs.io/en/latest/contribute/

**Comment by evgeni** [comment]
There is gitlab.com which we could use I guess. But all API requests require authentication.
If you would create a user and share the token I could use that user for the tests.

**Comment by thrix** [comment]
@evgeni thanks for working on this, could you make GITLAB_API configurable? I need version 3 ...

**Comment by evgeni** [comment]
@thrix sadly v3 API has no user events endpoint, so while I could, it would be worthless :(

**Comment by evgeni** [comment]
@psss added tests, but they obviously fail w/o a token :(

**Comment by psss** [comment]
That's great! Thanks, @evgeni. Sorry, I don't have much time today but I'll create the account next week. Then we can make the tests working.

**Comment by thrix** [comment]
@evgeni thanks, that is quite unfortunate :( we have just v3 available, anyway, thanks for the info

**Comment by evgeni** [comment]
@thrix sadly the search API of GitLab is not as feature-rich as GitHub, so you cannot search for stuff like "all issues created by user X in the timeframe Y-Z", thus I used the events api, which provides a nice stream of data for that.

And I feel with you, one of the GitLab instances I use is also v3 only, so it does not work there :(

Ref: https://docs.gitlab.com/ce/api/issues.html#list-issues

**Comment by evgeni** [comment]
@psss ping ;)

**Comment by psss** [comment]
Oh! Sorry, @evgeni! My last weeks were quite busy...
Here's the token for testing: x8mA6GVs3Dw2zXMYMoc8
Do you need anything else to be set up on the GitLab server?

**Comment by evgeni** [comment]
@psss cool, thanks! could you share the original account details (user/pass) too? then I can set up a test repo with test issues etc using the webUI instead of the API, which is easier.  (encrypt the data with gpg if you want to: C575A957E819BA18BF07E766A1B09B42333961E8 or E2FF 187B 5236 03AD 65D9  814B 81D0 CC18 450C E7AD)

**Comment by psss** [comment]
Sure, here you are:

Username: did.tester
Password: :mH7K8RyjE2W}k6m

We can change the password when the repo is ready.

**Comment by evgeni** [comment]
test failures are outside of test_gitlab.py :P

**Comment by psss** [comment]
Thanks for the patch, Evgeni!

**Comment by todoleza** [comment]
Thanks for the plugin. However I am unable to run the gitlab plugin against older {"version":"8.14.4","revision":"3ea6c8d"}, gitlab.com currently runs {"version":"9.4.0-rc3-ee","revision":"8ebdc5e"} with /api/v4 support.
I currently lack time to add backwards compatibility for /api/v3. Is there anyone willing to extend the plugin? Should I create different ticket for it?

**Comment by evgeni** [comment]
@todoleza I think a separate ticket is in order. I am personally not willing/interested to work on v3 support, but maybe others are.

**Comment by thrix** [comment]
do you mean reimplement activity log in the did module?

**Comment by todoleza** [comment]
Hello @thrix, I wasn't how big the reimplementation, if any, would be needed. Anyway, the instance I am using is said to be going upgraded soon, so there's small, if any, need to proceed here.
I am not creating separate ticket then. Thanks

**Pull request merged**
